steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vytvorit-qr:$COMMIT_SHA', '.']

  # Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vytvorit-qr:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'vytvorit-qr'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vytvorit-qr:$COMMIT_SHA'
      - '--region'
      - 'europe-central2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'

  # Map custom domain to Cloud Run service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'domain-mappings'
      - 'create'
      - '--service'
      - 'vytvorit-qr'
      - '--domain'
      - 'qr.aox.cz'
      - '--region'
      - 'europe-central2'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/vytvorit-qr:$COMMIT_SHA'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY
