name: Deploy to Google Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: europe-west1
  SERVICE: vytvorit-qr
  REGION: europe-west1

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and Push
        run: |-
          docker build -t "gcr.io/$PROJECT_ID/$SERVICE:$GITHUB_SHA" .
          docker push "gcr.io/$PROJECT_ID/$SERVICE:$GITHUB_SHA"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}
          flags: '--port 80 --memory 512Mi --cpu 1 --max-instances 10 --allow-unauthenticated'

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}

      - name: Setup Domain
        if: github.ref == 'refs/heads/main'
        run: |
          # Map custom domain to Cloud Run service
          gcloud run domain-mappings create \
            --service=$SERVICE \
            --domain=qr.aox.cz \
            --region=$REGION \
            --project=$PROJECT_ID || echo "Domain mapping may already exist"
